const sectorNames = {
    "sector_1": "Andromeda",
    "sector_2": "Antlia",
    "sector_3": "Apus",
    "sector_4": "Aquarius",
    "sector_5": "Aquila",
    "sector_6": "Ara",
    "sector_7": "Aries",
    "sector_8": "Auriga",
    "sector_9": "Bootes",
    "sector_10": "Caelum",
    "sector_11": "Camelopardalis",
    "sector_12": "Cancer",
    "sector_13": "Canes Venatici",
    "sector_14": "Canis Major",
    "sector_15": "Canis Minor",
    "sector_16": "Capricornus",
    "sector_17": "Carina",
    "sector_18": "Cassiopeia",
    "sector_19": "Centaurus",
    "sector_20": "Cepheus",
    "sector_21": "Cetus",
    "sector_22": "Chamaeleon",
    "sector_23": "Circinus",
    "sector_24": "Columba",
    "sector_25": "Coma Berenices",
    "sector_26": "Corona Australis",
    "sector_27": "Corona Borealis",
    "sector_28": "Corvus",
    "sector_29": "Crater",
    "sector_30": "Crux",
    "sector_31": "Cygnus",
    "sector_32": "Delphinus",
    "sector_33": "Dorado",
    "sector_34": "Draco",
    "sector_35": "Equuleus",
    "sector_36": "Eridanus",
    "sector_37": "Fornax",
    "sector_38": "Gemini",
    "sector_39": "Grus",
    "sector_40": "Hercules",
    "sector_41": "Horologium",
    "sector_42": "Hydra",
    "sector_43": "Hydrus",
    "sector_44": "Indus",
    "sector_45": "Lacerta",
    "sector_46": "Leo",
    "sector_47": "Leo Minor",
    "sector_48": "Lepus",
    "sector_49": "Libra",
    "sector_50": "Lupus",
    "sector_51": "Lynx",
    "sector_52": "Lyra",
    "sector_53": "Mensa",
    "sector_54": "Microscopium",
    "sector_55": "Monoceros",
    "sector_56": "Musca",
    "sector_57": "Norma",
    "sector_58": "Octans",
    "sector_59": "Ophiuchus",
    "sector_60": "Orion",
    "sector_61": "Pavo",
    "sector_62": "Pegasus",
    "sector_63": "Perseus",
    "sector_64": "Phoenix",
    "sector_65": "Pictor",
    "sector_66": "Pisces",
    "sector_67": "Piscis Austrinus",
    "sector_68": "Puppis",
    "sector_69": "Pyxis",
    "sector_70": "Reticulum",
    "sector_71": "Sagitta",
    "sector_72": "Sagittarius",
    "sector_73": "Scorpius",
    "sector_74": "Sculptor",
    "sector_75": "Scutum",
    "sector_76": "Serpens",
    "sector_77": "Sextans",
    "sector_78": "Taurus",
    "sector_79": "Telescopium",
    "sector_80": "Triangulum",
    "sector_81": "Triangulum Australe",
    "sector_82": "Tucana",
    "sector_83": "Ursa Major",
    "sector_84": "Ursa Minor",
    "sector_85": "Vela",
    "sector_86": "Virgo",
    "sector_87": "Volans",
    "sector_88": "Vulpecula",
    "sector_89": "Sirius",
    "sector_90": "Canopus",
    "sector_91": "Arcturus",
    "sector_92": "Vega",
    "sector_93": "Capella",
    "sector_94": "Rigel",
    "sector_95": "Procyon",
    "sector_96": "Achernar",
    "sector_97": "Betelgeuse",
    "sector_98": "Hadar",
    "sector_99": "Altair",
    "sector_100": "Antares"
}

export function GetSectorNameByWaveIndex(waveIndex) {
    // Convert wave index to sector number (1-based)
    const sectorNumber = (waveIndex % 100) + 1;
    const sectorKey = `sector_${sectorNumber}`;
    return sectorNames[sectorKey] || "Unknown Sector";
}

export { sectorNames };